//////////////////////////////////////////////////////////////////////
// This file is part of Remere's Map Editor
//////////////////////////////////////////////////////////////////////

#include "app/main.h"

#include "brushes/carpet/carpet_brush.h"

//=============================================================================
// Border lookup tables

void CarpetBrush::init() {
	CarpetBrush::carpet_types[0] // 0
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_NORTHWEST] // 1
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_NORTH] // 10
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_NORTH | TILE_NORTHWEST] // 11
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_NORTHEAST] // 100
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_NORTHEAST | TILE_NORTHWEST] // 101
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_NORTHEAST | TILE_NORTH] // 110
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_WEST] // 1000
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_WEST | TILE_NORTHWEST] // 1001
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_WEST | TILE_NORTH] // 1010
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_WEST | TILE_NORTHEAST] // 1100
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1110
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_EAST] // 10000
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_EAST | TILE_NORTHWEST] // 10001
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_EAST | TILE_NORTH] // 10010
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 10011
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_EAST | TILE_NORTHEAST] // 10100
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 10101
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 10110
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 10111
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_EAST | TILE_WEST] // 11000
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 11001
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_EAST | TILE_WEST | TILE_NORTH] // 11010
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 11011
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 11100
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 11101
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 11110
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 11111
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHWEST] // 100000
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_NORTHWEST] // 100001
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_NORTH] // 100010
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 100011
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_NORTHEAST] // 100100
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 100101
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 100110
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 100111
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_WEST] // 101000
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 101001
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 101010
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 101011
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 101100
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 101101
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 101110
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 101111
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST] // 110000
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 110001
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 110010
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 110011
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 110100
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 110101
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 110110
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 110111
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 111000
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 111001
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 111010
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 111011
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 111100
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 111101
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 111110
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111111
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH] // 1000000
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_NORTHWEST] // 1000001
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_NORTH] // 1000010
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_NORTH | TILE_NORTHWEST] // 1000011
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_NORTHEAST] // 1000100
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_NORTHEAST | TILE_NORTHWEST] // 1000101
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH] // 1000110
		= NORTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1000111
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_WEST] // 1001000
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_WEST | TILE_NORTHWEST] // 1001001
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_WEST | TILE_NORTH] // 1001010
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1001011
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST] // 1001100
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1001101
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1001110
		= NORTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1001111
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST] // 1010000
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_NORTHWEST] // 1010001
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_NORTH] // 1010010
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1010011
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST] // 1010100
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1010101
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1010110
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1010111
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_WEST] // 1011000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1011001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH] // 1011010
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011011
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1011100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1011101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1011110
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1011111
		= NORTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST] // 1100000
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHWEST] // 1100001
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH] // 1100010
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 1100011
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST] // 1100100
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1100101
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 1100110
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1100111
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST] // 1101000
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 1101001
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 1101010
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1101011
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 1101100
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101101
		= SOUTHWEST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1101110
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1101111
		= WEST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST] // 1110000
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 1110001
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 1110010
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1110011
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 1110100
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1110101
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1110110
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1110111
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 1111000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1111001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 1111010
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1111011
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1111100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1111101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1111110
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111111
		= NORTHWEST_DIAGONAL;

	CarpetBrush::carpet_types[TILE_SOUTHEAST]
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_NORTHWEST] // 1
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_NORTH] // 10
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_NORTH | TILE_NORTHWEST] // 11
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_NORTHEAST] // 100
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_NORTHEAST | TILE_NORTHWEST] // 101
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_NORTHEAST | TILE_NORTH] // 110
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_WEST] // 1000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHWEST] // 1001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTH] // 1010
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST] // 1100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1110
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST] // 10000
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHWEST] // 10001
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTH] // 10010
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 10011
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST] // 10100
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 10101
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 10110
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 10111
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST] // 11000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 11001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTH] // 11010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 11011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 11100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 11101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 11110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 11111
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST] // 100000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHWEST] // 100001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTH] // 100010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 100011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST] // 100100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 100101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 100110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 100111
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST] // 101000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 101001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 101010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 101011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 101100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 101101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 101110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 101111
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST] // 110000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 110001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 110010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 110011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 110100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 110101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 110110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 110111
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 111000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 111001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 111010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 111011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 111100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 111101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 111110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111111
		= NORTHEAST_DIAGONAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH] // 1000000
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHWEST] // 1000001
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTH] // 1000010
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTH | TILE_NORTHWEST] // 1000011
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST] // 1000100
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST | TILE_NORTHWEST] // 1000101
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH] // 1000110
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1000111
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST] // 1001000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHWEST] // 1001001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTH] // 1001010
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1001011
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST] // 1001100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1001101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1001110
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1001111
		= CARPET_CENTER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST] // 1010000
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHWEST] // 1010001
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTH] // 1010010
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1010011
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST] // 1010100
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1010101
		= SOUTHEAST_CORNER;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1010110
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1010111
		= EAST_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST] // 1011000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1011001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH] // 1011010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1011100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1011101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1011110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1011111
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST] // 1100000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHWEST] // 1100001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH] // 1100010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 1100011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST] // 1100100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1100101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 1100110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1100111
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST] // 1101000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 1101001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 1101010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1101011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 1101100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1101110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1101111
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST] // 1110000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 1110001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 1110010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1110011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 1110100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1110101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1110110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1110111
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 1111000
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1111001
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 1111010
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1111011
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1111100
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1111101
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1111110
		= SOUTH_HORIZONTAL;
	CarpetBrush::carpet_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111111
		= SOUTHEAST_DIAGONAL;
}
