//////////////////////////////////////////////////////////////////////
// This file is part of Remere's Map Editor
//////////////////////////////////////////////////////////////////////

#include "app/main.h"

#include "ui/map_statistics_dialog.h"
#include "ui/gui.h"
#include "ui/dialog_util.h"
#include "map/map_statistics.h"

#include <wx/wx.h>
#include <sstream>

extern GUI g_gui;

void MapStatisticsDialog::Show(wxWindow* parent) {
	if (!g_gui.IsEditorOpen()) {
		return;
	}

	g_gui.CreateLoadBar("Collecting data...");

	Map* map = &g_gui.GetCurrentMap();
	MapStatistics stats = MapStatisticsCollector::Collect(map);

	g_gui.DestroyLoadBar();

	std::ostringstream os;
	os.setf(std::ios::fixed, std::ios::floatfield);
	os.precision(2);
	os << "Map statistics for the map \"" << map->getMapDescription() << "\"\n";
	os << "\tTile data:\n";
	os << "\t\tTotal number of tiles: " << stats.tile_count << "\n";
	os << "\t\tNumber of pathable tiles: " << stats.walkable_tile_count << "\n";
	os << "\t\tNumber of unpathable tiles: " << stats.blocking_tile_count << "\n";
	if (stats.percent_pathable >= 0.0) {
		os << "\t\tPercent walkable tiles: " << stats.percent_pathable << "%\n";
	}
	os << "\t\tDetailed tiles: " << stats.detailed_tile_count << "\n";
	if (stats.percent_detailed >= 0.0) {
		os << "\t\tPercent detailed tiles: " << stats.percent_detailed << "%\n";
	}

	os << "\tItem data:\n";
	os << "\t\tTotal number of items: " << stats.item_count << "\n";
	os << "\t\tNumber of moveable tiles: " << stats.loose_item_count << "\n";
	os << "\t\tNumber of depots: " << stats.depot_count << "\n";
	os << "\t\tNumber of containers: " << stats.container_count << "\n";
	os << "\t\tNumber of items with Action ID: " << stats.action_item_count << "\n";
	os << "\t\tNumber of items with Unique ID: " << stats.unique_item_count << "\n";

	os << "\tCreature data:\n";
	os << "\t\tTotal creature count: " << stats.creature_count << "\n";
	os << "\t\tTotal spawn count: " << stats.spawn_count << "\n";
	if (stats.creatures_per_spawn >= 0) {
		os << "\t\tMean creatures per spawn: " << stats.creatures_per_spawn << "\n";
	}

	os << "\tTown/House data:\n";
	os << "\t\tTotal number of towns: " << stats.town_count << "\n";
	os << "\t\tTotal number of houses: " << stats.house_count << "\n";
	if (stats.houses_per_town >= 0) {
		os << "\t\tMean houses per town: " << stats.houses_per_town << "\n";
	}
	os << "\t\tTotal amount of housetiles: " << stats.total_house_sqm << "\n";
	if (stats.sqm_per_house >= 0) {
		os << "\t\tMean tiles per house: " << stats.sqm_per_house << "\n";
	}
	if (stats.sqm_per_town >= 0) {
		os << "\t\tMean tiles per town: " << stats.sqm_per_town << "\n";
	}

	if (stats.largest_town) {
		os << "\t\tLargest Town: \"" << std::string(stats.largest_town->getName()) << "\" (" << stats.largest_town_size << " sqm)\n";
	}
	if (stats.largest_house) {
		os << "\t\tLargest House: \"" << stats.largest_house->name << "\" (" << stats.largest_house_size << " sqm)\n";
	}

	os << "\n";
	os << "Generated by Remere's Map Editor version " + __RME_VERSION__ + "\n";

	wxDialog* dg = newd wxDialog(parent, wxID_ANY, "Map Statistics", wxDefaultPosition, wxDefaultSize, wxRESIZE_BORDER | wxCAPTION | wxCLOSE_BOX);
	wxSizer* topsizer = newd wxBoxSizer(wxVERTICAL);
	wxTextCtrl* text_field = newd wxTextCtrl(dg, wxID_ANY, wxstr(os.str()), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE | wxTE_READONLY);
	text_field->SetMinSize(wxSize(400, 300));
	topsizer->Add(text_field, wxSizerFlags(5).Expand());

	wxSizer* choicesizer = newd wxBoxSizer(wxHORIZONTAL);
	wxButton* export_button = newd wxButton(dg, wxID_OK, "Export as XML");
	choicesizer->Add(export_button, wxSizerFlags(1).Center());
	export_button->SetToolTip("Not implemented yet");
	export_button->Enable(false);
	wxButton* okBtn = newd wxButton(dg, wxID_CANCEL, "OK");
	okBtn->SetToolTip("Close this window");
	choicesizer->Add(okBtn, wxSizerFlags(1).Center());
	topsizer->Add(choicesizer, wxSizerFlags(1).Center());
	dg->SetSizerAndFit(topsizer);
	dg->Centre(wxBOTH);

	int ret = dg->ShowModal();

	if (ret == wxID_OK) {
	} else if (ret == wxID_CANCEL) {
	}

	dg->Destroy();
}
