//////////////////////////////////////////////////////////////////////
// This file is part of Remere's Map Editor
//////////////////////////////////////////////////////////////////////

#include "app/main.h"

#include "brushes/ground/ground_brush.h"

//=============================================================================
// Border lookup tables

void GroundBrush::init() {
	GroundBrush::border_types[0] // 0
		= BORDER_NONE;
	GroundBrush::border_types[TILE_NORTHWEST] // 1
		= NORTHWEST_CORNER;
	GroundBrush::border_types[TILE_NORTH] // 10
		= NORTH_HORIZONTAL;
	GroundBrush::border_types[TILE_NORTH | TILE_NORTHWEST] // 11
		= NORTH_HORIZONTAL;
	GroundBrush::border_types[TILE_NORTHEAST] // 100
		= NORTHEAST_CORNER;
	GroundBrush::border_types[TILE_NORTHEAST | TILE_NORTHWEST] // 101
		= NORTHWEST_CORNER | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_NORTHEAST | TILE_NORTH] // 110
		= NORTH_HORIZONTAL;
	GroundBrush::border_types[TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111
		= NORTH_HORIZONTAL;
	GroundBrush::border_types[TILE_WEST] // 1000
		= WEST_HORIZONTAL;
	GroundBrush::border_types[TILE_WEST | TILE_NORTHWEST] // 1001
		= WEST_HORIZONTAL;
	GroundBrush::border_types[TILE_WEST | TILE_NORTH] // 1010
		= NORTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011
		= NORTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_WEST | TILE_NORTHEAST] // 1100
		= WEST_HORIZONTAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101
		= WEST_HORIZONTAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1110
		= NORTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111
		= NORTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_EAST] // 10000
		= EAST_HORIZONTAL;
	GroundBrush::border_types[TILE_EAST | TILE_NORTHWEST] // 10001
		= NORTHWEST_CORNER | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_EAST | TILE_NORTH] // 10010
		= NORTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 10011
		= NORTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_EAST | TILE_NORTHEAST] // 10100
		= EAST_HORIZONTAL;
	GroundBrush::border_types[TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 10101
		= NORTHWEST_CORNER | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 10110
		= NORTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 10111
		= NORTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_EAST | TILE_WEST] // 11000
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 11001
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_EAST | TILE_WEST | TILE_NORTH] // 11010
		= NORTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 11011
		= NORTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 11100
		= EAST_HORIZONTAL | WEST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 11101
		= EAST_HORIZONTAL | WEST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 11110
		= NORTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 11111
		= NORTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHWEST] // 100000
		= SOUTHWEST_CORNER;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_NORTHWEST] // 100001
		= SOUTHWEST_CORNER | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_NORTH] // 100010
		= SOUTHWEST_CORNER | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 100011
		= SOUTHWEST_CORNER | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_NORTHEAST] // 100100
		= SOUTHWEST_CORNER | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 100101
		= SOUTHWEST_CORNER | NORTHEAST_CORNER << 8 | NORTHWEST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 100110
		= SOUTHWEST_CORNER | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 100111
		= SOUTHWEST_CORNER | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_WEST] // 101000
		= WEST_HORIZONTAL;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 101001
		= WEST_HORIZONTAL;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 101010
		= NORTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 101011
		= NORTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 101100
		= WEST_HORIZONTAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 101101
		= WEST_HORIZONTAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 101110
		= NORTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 101111
		= NORTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST] // 110000
		= SOUTHWEST_CORNER | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 110001
		= SOUTHWEST_CORNER | EAST_HORIZONTAL << 8 | NORTHWEST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 110010
		= SOUTHWEST_CORNER | NORTHEAST_DIAGONAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 110011
		= SOUTHWEST_CORNER | NORTHEAST_DIAGONAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 110100
		= SOUTHWEST_CORNER | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 110101
		= SOUTHWEST_CORNER | EAST_HORIZONTAL << 8 | NORTHWEST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 110110
		= SOUTHWEST_CORNER | NORTHEAST_DIAGONAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 110111
		= SOUTHWEST_CORNER | NORTHEAST_DIAGONAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 111000
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 111001
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 111010
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 111011
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 111100
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 111101
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 111110
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111111
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH] // 1000000
		= SOUTH_HORIZONTAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_NORTHWEST] // 1000001
		= SOUTH_HORIZONTAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_NORTH] // 1000010
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_NORTH | TILE_NORTHWEST] // 1000011
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_NORTHEAST] // 1000100
		= SOUTH_HORIZONTAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_NORTHEAST | TILE_NORTHWEST] // 1000101
		= SOUTH_HORIZONTAL | NORTHEAST_CORNER << 8 | NORTHWEST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH] // 1000110
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1000111
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_WEST] // 1001000
		= SOUTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_WEST | TILE_NORTHWEST] // 1001001
		= SOUTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_WEST | TILE_NORTH] // 1001010
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1001011
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST] // 1001100
		= SOUTHWEST_DIAGONAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1001101
		= SOUTHWEST_DIAGONAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1001110
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1001111
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST] // 1010000
		= SOUTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_NORTHWEST] // 1010001
		= SOUTHEAST_DIAGONAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_NORTH] // 1010010
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1010011
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST] // 1010100
		= SOUTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1010101
		= SOUTHEAST_DIAGONAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1010110
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1010111
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_WEST] // 1011000
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1011001
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH] // 1011010
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16 | NORTH_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011011
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16 | NORTH_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1011100
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1011101
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1011110
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16 | NORTH_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1011111
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16 | NORTH_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST] // 1100000
		= SOUTH_HORIZONTAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHWEST] // 1100001
		= SOUTH_HORIZONTAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH] // 1100010
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 1100011
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST] // 1100100
		= SOUTH_HORIZONTAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1100101
		= SOUTH_HORIZONTAL | NORTHWEST_CORNER << 8 | NORTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 1100110
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1100111
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST] // 1101000
		= SOUTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 1101001
		= SOUTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 1101010
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1101011
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 1101100
		= SOUTHWEST_DIAGONAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101101
		= SOUTHWEST_DIAGONAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1101110
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1101111
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST] // 1110000
		= SOUTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 1110001
		= SOUTHEAST_DIAGONAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 1110010
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1110011
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 1110100
		= SOUTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1110101
		= SOUTHEAST_DIAGONAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1110110
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1110111
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 1111000
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1111001
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 1111010
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16 | WEST_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1111011
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16 | WEST_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1111100
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1111101
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1111110
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16 | WEST_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111111
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16 | WEST_HORIZONTAL << 24;

	GroundBrush::border_types[TILE_SOUTHEAST]
		= SOUTHEAST_CORNER;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_NORTHWEST] // 1
		= NORTHWEST_CORNER | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_NORTH] // 10
		= NORTH_HORIZONTAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_NORTH | TILE_NORTHWEST] // 11
		= NORTH_HORIZONTAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_NORTHEAST] // 100
		= NORTHEAST_CORNER | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_NORTHEAST | TILE_NORTHWEST] // 101
		= NORTHEAST_CORNER | NORTHWEST_CORNER << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_NORTHEAST | TILE_NORTH] // 110
		= NORTH_HORIZONTAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111
		= NORTH_HORIZONTAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_WEST] // 1000
		= WEST_HORIZONTAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHWEST] // 1001
		= WEST_HORIZONTAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTH] // 1010
		= NORTHWEST_DIAGONAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011
		= NORTHWEST_DIAGONAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST] // 1100
		= WEST_HORIZONTAL | NORTHEAST_CORNER << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101
		= WEST_HORIZONTAL | NORTHEAST_CORNER << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1110
		= NORTHWEST_DIAGONAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111
		= NORTHWEST_DIAGONAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST] // 10000
		= EAST_HORIZONTAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHWEST] // 10001
		= EAST_HORIZONTAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTH] // 10010
		= NORTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 10011
		= NORTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST] // 10100
		= EAST_HORIZONTAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 10101
		= EAST_HORIZONTAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 10110
		= NORTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 10111
		= NORTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST] // 11000
		= EAST_HORIZONTAL | WEST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 11001
		= EAST_HORIZONTAL | WEST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTH] // 11010
		= NORTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 11011
		= EAST_HORIZONTAL | WEST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 11100
		= EAST_HORIZONTAL | WEST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 11101
		= EAST_HORIZONTAL | WEST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 11110
		= NORTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 11111
		= NORTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST] // 100000
		= SOUTHWEST_CORNER | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHWEST] // 100001
		= SOUTHWEST_CORNER | NORTHWEST_CORNER << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTH] // 100010
		= SOUTHWEST_CORNER | NORTH_HORIZONTAL << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 100011
		= SOUTHWEST_CORNER | NORTH_HORIZONTAL << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST] // 100100
		= SOUTHWEST_CORNER | NORTHEAST_CORNER << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 100101
		= SOUTHWEST_CORNER | NORTHEAST_CORNER << 8 | NORTHWEST_CORNER << 16 | SOUTHEAST_CORNER << 24;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 100110
		= SOUTHWEST_CORNER | NORTH_HORIZONTAL << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 100111
		= SOUTHWEST_CORNER | NORTH_HORIZONTAL << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST] // 101000
		= WEST_HORIZONTAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 101001
		= WEST_HORIZONTAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 101010
		= NORTHWEST_DIAGONAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 101011
		= NORTHWEST_DIAGONAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 101100
		= WEST_HORIZONTAL | NORTHEAST_CORNER << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 101101
		= WEST_HORIZONTAL | NORTHEAST_CORNER << 8 | SOUTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 101110
		= NORTHWEST_DIAGONAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 101111
		= NORTHWEST_DIAGONAL | SOUTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST] // 110000
		= SOUTHWEST_CORNER | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 110001
		= SOUTHWEST_CORNER | EAST_HORIZONTAL << 8 | NORTHWEST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 110010
		= SOUTHWEST_CORNER | NORTHEAST_DIAGONAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 110011
		= SOUTHWEST_CORNER | NORTHEAST_DIAGONAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 110100
		= SOUTHWEST_CORNER | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 110101
		= SOUTHWEST_CORNER | EAST_HORIZONTAL << 8 | NORTHWEST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 110110
		= SOUTHWEST_CORNER | NORTHEAST_DIAGONAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 110111
		= SOUTHWEST_CORNER | NORTHEAST_DIAGONAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 111000
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 111001
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 111010
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 111011
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 111100
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 111101
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 111110
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111111
		= WEST_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH] // 1000000
		= SOUTH_HORIZONTAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHWEST] // 1000001
		= SOUTH_HORIZONTAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTH] // 1000010
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTH | TILE_NORTHWEST] // 1000011
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST] // 1000100
		= SOUTH_HORIZONTAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST | TILE_NORTHWEST] // 1000101
		= SOUTH_HORIZONTAL | NORTHEAST_CORNER << 8 | NORTHWEST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH] // 1000110
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1000111
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST] // 1001000
		= SOUTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHWEST] // 1001001
		= SOUTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTH] // 1001010
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1001011
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST] // 1001100
		= SOUTHWEST_DIAGONAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1001101
		= SOUTHWEST_DIAGONAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1001110
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1001111
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST] // 1010000
		= SOUTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHWEST] // 1010001
		= SOUTHEAST_DIAGONAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTH] // 1010010
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1010011
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST] // 1010100
		= SOUTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1010101
		= SOUTHEAST_DIAGONAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1010110
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1010111
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST] // 1011000
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1011001
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH] // 1011010
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16 | NORTH_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011011
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16 | NORTH_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1011100
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1011101
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1011110
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16 | NORTH_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1011111
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | EAST_HORIZONTAL << 16 | NORTH_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST] // 1100000
		= SOUTH_HORIZONTAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHWEST] // 1100001
		= SOUTH_HORIZONTAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH] // 1100010
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 1100011
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST] // 1100100
		= SOUTH_HORIZONTAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1100101
		= SOUTH_HORIZONTAL | NORTHWEST_CORNER << 8 | NORTHEAST_CORNER << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 1100110
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1100111
		= SOUTH_HORIZONTAL | NORTH_HORIZONTAL << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST] // 1101000
		= SOUTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 1101001
		= SOUTHWEST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 1101010
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1101011
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 1101100
		= SOUTHWEST_DIAGONAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101101
		= SOUTHWEST_DIAGONAL | NORTHEAST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1101110
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1101111
		= SOUTH_HORIZONTAL | WEST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST] // 1110000
		= SOUTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 1110001
		= SOUTHEAST_DIAGONAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 1110010
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1110011
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 1110100
		= SOUTHEAST_DIAGONAL;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1110101
		= SOUTHEAST_DIAGONAL | NORTHWEST_CORNER << 8;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1110110
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1110111
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 1111000
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1111001
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 1111010
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16 | WEST_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1111011
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16 | WEST_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1111100
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1111101
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | WEST_HORIZONTAL << 16;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1111110
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16 | WEST_HORIZONTAL << 24;
	GroundBrush::border_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111111
		= SOUTH_HORIZONTAL | EAST_HORIZONTAL << 8 | NORTH_HORIZONTAL << 16 | WEST_HORIZONTAL << 24;
}
