#ifndef RME_UI_DIALOGS_OUTFIT_SELECTION_GRID_H_
#define RME_UI_DIALOGS_OUTFIT_SELECTION_GRID_H_

#include "app/main.h"
#include "game/outfit.h"
#include "game/preview_preferences.h"
#include "util/nanovg_canvas.h"
#include <vector>
#include <unordered_map>

class OutfitChooserDialog; // Forward declaration

struct OutfitItem {
	int lookType;
	wxString name;
	int layers;
};

class OutfitSelectionGrid : public NanoVGCanvas {
public:
	OutfitSelectionGrid(wxWindow* parent, OutfitChooserDialog* owner, bool is_favorites = false);
	void UpdateFilter(const wxString& filter, bool colorable_only);
	void UpdateVirtualSize();
	std::vector<OutfitItem> all_outfits;
	std::vector<OutfitItem> filtered_outfits;
	std::vector<FavoriteItem> favorite_items;
	bool is_favorites;
	int selected_index;

protected:
	void OnNanoVGPaint(NVGcontext* vg, int width, int height) override;
	wxSize DoGetBestClientSize() const override;

private:
	void OnSize(wxSizeEvent& event);
	void OnMouse(wxMouseEvent& event);
	void OnMotion(wxMouseEvent& event);
	void OnContextMenu(wxContextMenuEvent& event);

	int HitTest(int x, int y) const;
	wxRect GetItemRect(int index) const;

	// Helper to create RGBA buffer from wxImage (generated by SpriteIconGenerator)
	int GetOrCreateOutfitImage(NVGcontext* vg, int lookType, const Outfit& outfit);

	OutfitChooserDialog* owner;
	int columns;
	int item_width;
	int item_height;
	int padding;
	int hover_index;
};

#endif
