//////////////////////////////////////////////////////////////////////
// This file is part of Remere's Map Editor
//////////////////////////////////////////////////////////////////////

#include "app/main.h"

#include "brushes/table/table_brush.h"

//=============================================================================
// Border lookup tables

void TableBrush::init() {
	TableBrush::table_types[0] // 0
		= TABLE_ALONE;
	TableBrush::table_types[TILE_NORTHWEST] // 1
		= TABLE_ALONE;
	TableBrush::table_types[TILE_NORTH] // 10
		= TABLE_SOUTH_END;
	TableBrush::table_types[TILE_NORTH | TILE_NORTHWEST] // 11
		= TABLE_SOUTH_END;
	TableBrush::table_types[TILE_NORTHEAST] // 100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_NORTHEAST | TILE_NORTHWEST] // 101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_NORTHEAST | TILE_NORTH] // 110
		= TABLE_SOUTH_END;
	TableBrush::table_types[TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111
		= TABLE_SOUTH_END;
	TableBrush::table_types[TILE_WEST] // 1000
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_WEST | TILE_NORTHWEST] // 1001
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_WEST | TILE_NORTH] // 1010
		= TABLE_ALONE;
	TableBrush::table_types[TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_WEST | TILE_NORTHEAST] // 1100
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_EAST] // 10000
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_EAST | TILE_NORTHWEST] // 10001
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_EAST | TILE_NORTH] // 10010
		= TABLE_ALONE;
	TableBrush::table_types[TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 10011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_EAST | TILE_NORTHEAST] // 10100
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 10101
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 10110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 10111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_EAST | TILE_WEST] // 11000
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 11001
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_EAST | TILE_WEST | TILE_NORTH] // 11010
		= TABLE_ALONE;
	TableBrush::table_types[TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 11011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 11100
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 11101
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 11110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 11111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHWEST] // 100000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_NORTHWEST] // 100001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_NORTH] // 100010
		= TABLE_SOUTH_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 100011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_NORTHEAST] // 100100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 100101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 100110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 100111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_WEST] // 101000
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 101001
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 101010
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 101011
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 101100
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 101101
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 101110
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 101111
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST] // 110000
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 110001
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 110010
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 110011
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 110100
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 110101
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 110110
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 110111
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 111000
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 111001
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 111010
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 111011
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 111100
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 111101
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 111110
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111111
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTH] // 1000000
		= TABLE_NORTH_END;
	TableBrush::table_types[TILE_SOUTH | TILE_NORTHWEST] // 1000001
		= TABLE_NORTH_END;
	TableBrush::table_types[TILE_SOUTH | TILE_NORTH] // 1000010
		= TABLE_VERTICAL;
	TableBrush::table_types[TILE_SOUTH | TILE_NORTH | TILE_NORTHWEST] // 1000011
		= TABLE_VERTICAL;
	TableBrush::table_types[TILE_SOUTH | TILE_NORTHEAST] // 1000100
		= TABLE_NORTH_END;
	TableBrush::table_types[TILE_SOUTH | TILE_NORTHEAST | TILE_NORTHWEST] // 1000101
		= TABLE_NORTH_END;
	TableBrush::table_types[TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH] // 1000110
		= TABLE_VERTICAL;
	TableBrush::table_types[TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1000111
		= TABLE_VERTICAL;
	TableBrush::table_types[TILE_SOUTH | TILE_WEST] // 1001000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_WEST | TILE_NORTHWEST] // 1001001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_WEST | TILE_NORTH] // 1001010
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1001011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST] // 1001100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1001101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1001110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1001111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST] // 1010000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_NORTHWEST] // 1010001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_NORTH] // 1010010
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1010011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST] // 1010100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1010101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1010110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1010111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_WEST] // 1011000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1011001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH] // 1011010
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1011100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1011101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1011110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1011111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST] // 1100000
		= TABLE_NORTH_END;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHWEST] // 1100001
		= TABLE_NORTH_END;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH] // 1100010
		= TABLE_VERTICAL;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 1100011
		= TABLE_VERTICAL;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST] // 1100100
		= TABLE_NORTH_END;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1100101
		= TABLE_NORTH_END;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 1100110
		= TABLE_VERTICAL;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1100111
		= TABLE_VERTICAL;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST] // 1101000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 1101001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 1101010
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1101011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 1101100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1101110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1101111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST] // 1110000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 1110001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 1110010
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1110011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 1110100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1110101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1110110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1110111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 1111000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1111001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 1111010
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1111011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1111100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1111101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1111110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111111
		= TABLE_ALONE;

	TableBrush::table_types[TILE_SOUTHEAST]
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_NORTHWEST] // 1
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_NORTH] // 10
		= TABLE_SOUTH_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_NORTH | TILE_NORTHWEST] // 11
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_NORTHEAST] // 100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_NORTHEAST | TILE_NORTHWEST] // 101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_NORTHEAST | TILE_NORTH] // 110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_WEST] // 1000
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHWEST] // 1001
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTH] // 1010
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST] // 1100
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1110
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST] // 10000
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHWEST] // 10001
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTH] // 10010
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 10011
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST] // 10100
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 10101
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 10110
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 10111
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST] // 11000
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 11001
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTH] // 11010
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 11011
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 11100
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 11101
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 11110
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 11111
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST] // 100000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHWEST] // 100001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTH] // 100010
		= TABLE_SOUTH_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 100011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST] // 100100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 100101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 100110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 100111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST] // 101000
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 101001
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 101010
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 101011
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 101100
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 101101
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 101110
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 101111
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST] // 110000
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 110001
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 110010
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 110011
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 110100
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 110101
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 110110
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 110111
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 111000
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 111001
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 111010
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 111011
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 111100
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 111101
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 111110
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 111111
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH] // 1000000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHWEST] // 1000001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTH] // 1000010
		= TABLE_SOUTH_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTH | TILE_NORTHWEST] // 1000011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST] // 1000100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST | TILE_NORTHWEST] // 1000101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH] // 1000110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1000111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST] // 1001000
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHWEST] // 1001001
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTH] // 1001010
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1001011
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST] // 1001100
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1001101
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1001110
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1001111
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST] // 1010000
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHWEST] // 1010001
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTH] // 1010010
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1010011
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST] // 1010100
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1010101
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1010110
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1010111
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST] // 1011000
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1011001
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH] // 1011010
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1011011
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1011100
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1011101
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1011110
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1011111
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST] // 1100000
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHWEST] // 1100001
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH] // 1100010
		= TABLE_SOUTH_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTH | TILE_NORTHWEST] // 1100011
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST] // 1100100
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1100101
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH] // 1100110
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1100111
		= TABLE_ALONE;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST] // 1101000
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHWEST] // 1101001
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH] // 1101010
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1101011
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST] // 1101100
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1101101
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1101110
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1101111
		= TABLE_EAST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST] // 1110000
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHWEST] // 1110001
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH] // 1110010
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTH | TILE_NORTHWEST] // 1110011
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST] // 1110100
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTHWEST] // 1110101
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH] // 1110110
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1110111
		= TABLE_WEST_END;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST] // 1111000
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHWEST] // 1111001
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH] // 1111010
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTH | TILE_NORTHWEST] // 1111011
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST] // 1111100
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTHWEST] // 1111101
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH] // 1111110
		= TABLE_HORIZONTAL;
	TableBrush::table_types[TILE_SOUTHEAST | TILE_SOUTH | TILE_SOUTHWEST | TILE_EAST | TILE_WEST | TILE_NORTHEAST | TILE_NORTH | TILE_NORTHWEST] // 1111111
		= TABLE_HORIZONTAL;
}
